services:
  h2o-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
      - crystal-cache:/home/crystal/.cache
    working_dir: /workspace
    command: crystal spec
    environment:
      - CI=true
      # Test server host configuration
      - TEST_HTTP2_HOST=localhost
      - TEST_HTTP2_PORT=443
      - TEST_HTTP1_HOST=localhost
      - TEST_HTTP1_PORT=80
      - TEST_H2_ONLY_HOST=localhost
      - TEST_H2_ONLY_PORT=8447
      - TEST_CADDY_HOST=localhost
      - TEST_CADDY_PORT=8444
      # Timeout configuration
      - TEST_CLIENT_TIMEOUT_MS=5000
      - TEST_FAST_TIMEOUT_MS=1000
      # Debug configuration
      - TEST_DEBUG=${TEST_DEBUG:-false}
    networks:
      - default

  crystal:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
      - crystal-cache:/home/crystal/.cache
    working_dir: /workspace
    command: tail -f /dev/null
    ports:
      - "8080:8080"   # httpbin
      - "8443:8443"   # nginx HTTP/2
      - "8445:8445"   # nginx HTTP/1.1
    environment:
      - CI=true

  h2o-docs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
      - crystal-cache:/home/crystal/.cache
      - ./docs:/workspace/docs
    working_dir: /workspace
    command: crystal docs
    ports:
      - "8080:8080"

volumes:
  crystal-cache:
