services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    volumes:
      - .:/workspace
    working_dir: /workspace
    depends_on:
      - httpbin
      - nghttpd
    environment:
      - TEST_HTTPBIN_URL=http://httpbin:80
      - TEST_NGHTTPD_URL=https://nghttpd:4430
      - H2O_VERIFY_SSL=false
    command: crystal spec

  httpbin:
    image: kennethreitz/httpbin
    platform: linux/amd64
    ports:
      - "8080:80"

  nghttpd:
    image: "svagi/nghttp2"
    platform: linux/amd64
    ports:
      - "8443:4430"
    volumes:
      - /Users/robcole/dev/h2o/spec/integration/ssl/cert.pem:/srv/cert.pem
      - /Users/robcole/dev/h2o/spec/integration/ssl/key.pem:/srv/key.pem
      - /Users/robcole/dev/h2o/spec/integration:/srv
    command:
      - "nghttpd"
      - "-v"
      - "--htdocs=/srv"
      - "4430"
      - "/srv/key.pem"
      - "/srv/cert.pem"

  h2spec:
    build:
      context: ./h2spec
    platform: linux/amd64
    command: -h nghttpd -p 4430 -k -t
    depends_on:
      - nghttpd
