services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    platform: linux/amd64
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    depends_on:
      - httpbin
      - nghttpd
      - nghttpd2
    environment:
      - TEST_HTTPBIN_URL=http://httpbin:80
      - TEST_NGHTTPD_URL=https://nghttpd:443
      - H2O_VERIFY_SSL=false
      - DOCKER_HOST=unix:///var/run/docker.sock
    privileged: true

  httpbin:
    image: kennethreitz/httpbin
    platform: linux/amd64
    ports:
      - "8080:80"

  nghttpd:
    image: "svagi/nghttp2"
    platform: linux/amd64
    ports:
      - "8443:443"
    volumes:
      - ./spec/integration/ssl/cert.pem:/srv/cert.pem
      - ./spec/integration/ssl/key.pem:/srv/key.pem
      - ./spec/integration:/srv
    command:
      - "nghttpd"
      - "-v"
      - "--htdocs=/srv"
      - "443"
      - "/srv/key.pem"
      - "/srv/cert.pem"
    networks:
      default:
        aliases:
          - test-0.example.com
          - test-1.example.com
          - test-2.example.com
          - test-3.example.com
          - test-4.example.com
          - test.example.com
          - example.com

  nghttpd2:
    image: "svagi/nghttp2"
    platform: linux/amd64
    ports:
      - "8444:4433"
    volumes:
      - ./spec/integration/ssl/cert.pem:/srv/cert.pem
      - ./spec/integration/ssl/key.pem:/srv/key.pem
      - ./spec/integration:/srv
    command:
      - "nghttpd"
      - "-v"
      - "--htdocs=/srv"
      - "4433"
      - "/srv/key.pem"
      - "/srv/cert.pem"
    networks:
      default:
        aliases:
          - secondexample.com

  h2spec:
    build:
      context: ./h2spec
    platform: linux/amd64
    command: -h nghttpd -p 4430 -k -t
    depends_on:
      - nghttpd
