version: '3.8'

services:
  nginx-h2:
    image: nginx:alpine
    ports:
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    command: ['nginx', '-g', 'daemon off;']

  httpbin-h2:
    image: kennethreitz/httpbin
    ports:
      - "8080:80"

  caddy-h2:
    image: caddy:alpine
    ports:
      - "8444:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    command: ['caddy', 'run', '--config', '/etc/caddy/Caddyfile']

  h2-only-server:
    image: node:18-alpine
    ports:
      - "8447:8447"
    volumes:
      - ./h2-only-server.js:/app/server.js
      - ./ssl:/app/ssl
    working_dir: /app
    environment:
      - PORT=8447
    command: ['node', 'server.js']
